# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/management.ManagementService/Register',
                request_serializer=service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=service__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/management.ManagementService/Login',
                request_serializer=service__pb2.LoginRequest.SerializeToString,
                response_deserializer=service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateRoom = channel.unary_unary(
                '/management.ManagementService/CreateRoom',
                request_serializer=service__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=service__pb2.RoomResponse.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/management.ManagementService/ListRooms',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.RoomListResponse.FromString,
                _registered_method=True)
        self.ValidateJoin = channel.unary_unary(
                '/management.ManagementService/ValidateJoin',
                request_serializer=service__pb2.JoinRequest.SerializeToString,
                response_deserializer=service__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.UserJoined = channel.unary_unary(
                '/management.ManagementService/UserJoined',
                request_serializer=service__pb2.JoinRequest.SerializeToString,
                response_deserializer=service__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.UserLeft = channel.unary_unary(
                '/management.ManagementService/UserLeft',
                request_serializer=service__pb2.JoinRequest.SerializeToString,
                response_deserializer=service__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.StoreMessage = channel.unary_unary(
                '/management.ManagementService/StoreMessage',
                request_serializer=service__pb2.MessageRequest.SerializeToString,
                response_deserializer=service__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.BlockUser = channel.unary_unary(
                '/management.ManagementService/BlockUser',
                request_serializer=service__pb2.BlockRequest.SerializeToString,
                response_deserializer=service__pb2.BlockResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Room Management (Client)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJoin(self, request, context):
        """Signaling / Internal
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserJoined(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserLeft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=service__pb2.RegisterRequest.FromString,
                    response_serializer=service__pb2.UserResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=service__pb2.LoginRequest.FromString,
                    response_serializer=service__pb2.LoginResponse.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=service__pb2.CreateRoomRequest.FromString,
                    response_serializer=service__pb2.RoomResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.RoomListResponse.SerializeToString,
            ),
            'ValidateJoin': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJoin,
                    request_deserializer=service__pb2.JoinRequest.FromString,
                    response_serializer=service__pb2.JoinResponse.SerializeToString,
            ),
            'UserJoined': grpc.unary_unary_rpc_method_handler(
                    servicer.UserJoined,
                    request_deserializer=service__pb2.JoinRequest.FromString,
                    response_serializer=service__pb2.JoinResponse.SerializeToString,
            ),
            'UserLeft': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLeft,
                    request_deserializer=service__pb2.JoinRequest.FromString,
                    response_serializer=service__pb2.JoinResponse.SerializeToString,
            ),
            'StoreMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMessage,
                    request_deserializer=service__pb2.MessageRequest.FromString,
                    response_serializer=service__pb2.MessageResponse.SerializeToString,
            ),
            'BlockUser': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockUser,
                    request_deserializer=service__pb2.BlockRequest.FromString,
                    response_serializer=service__pb2.BlockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'management.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('management.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/Register',
            service__pb2.RegisterRequest.SerializeToString,
            service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/Login',
            service__pb2.LoginRequest.SerializeToString,
            service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateRoom',
            service__pb2.CreateRoomRequest.SerializeToString,
            service__pb2.RoomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ListRooms',
            service__pb2.Empty.SerializeToString,
            service__pb2.RoomListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateJoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ValidateJoin',
            service__pb2.JoinRequest.SerializeToString,
            service__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserJoined(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/UserJoined',
            service__pb2.JoinRequest.SerializeToString,
            service__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserLeft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/UserLeft',
            service__pb2.JoinRequest.SerializeToString,
            service__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/StoreMessage',
            service__pb2.MessageRequest.SerializeToString,
            service__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/BlockUser',
            service__pb2.BlockRequest.SerializeToString,
            service__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
